version: '3'
services:
    gohello:
        build: .
        image: codebadger/go-hello
        networks:
            - reverseproxy
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.backend=go-hello"
            - "traefik.frontend.rule=Host:go-hello.wtakumi.io"
            - "traefik.docker.network=traefik_reverseproxy"
        ports:
        - "3000:3000"

networks:
    reverseproxy:
        external:
            name: traefik_reverseproxy