version: '3'
services:
    pythonhello:
        build: .
        networks:
            - reverseproxy
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.backend=pythonhello"
            - "traefik.frontend.rule=Host:python-hello.wtakumi.io"
            - "traefik.docker.network=traefik_reverseproxy"
        ports:
        - "5000:5000"
    redis:
        image: "redis:alpine"

networks:
    reverseproxy:
          external:
              name: traefik_reverseproxy